// Closed set of activity event types (append-only log). See docs/01-architecture.md §5.

export const EVENT_TYPES = [
  "task.created",
  "task.updated",
  "task.completed",
  "task.reopened",
  "task.archived",
  "task.restored",
  "task.deleted",
  "goal.created",
  "goal.updated",
  "goal.status_changed",
  "goal.archived",
  "goal.restored",
  "goal.deleted",
  "milestone.created",
  "milestone.completed",
  "milestone.reopened",
  "milestone.deleted",
  "target.created",
  "target.updated",
  "target.archived",
  "target.restored",
  "target.deleted",
  "session.logged",
  "session.deleted",
  "routine.item_completed",
  "routine.item_skipped",
  "routine.item_reset",
  "project.created",
  "project.updated",
  "project.status_changed",
  "project.archived",
  "project.restored",
  "project.deleted",
  "idea.created",
  "idea.updated",
  "idea.status_changed",
  "idea.converted",
  "idea.deleted",
  "decision.recorded",
  "decision.updated",
  "decision.deleted",
  "note.created",
  "note.updated",
  "note.archived",
  "note.restored",
  "note.deleted",
  "skill.created",
  "skill.updated",
  "skill.level_changed",
  "skill.topic_completed",
  "skill.archived",
  "skill.restored",
  "skill.deleted",
  "inbox.captured",
  "inbox.processed",
  "inbox.discarded",
  "entity.linked",
  "entity.unlinked",
] as const;

export type EventType = (typeof EVENT_TYPES)[number];

/** Short past-tense verb for timeline rendering. */
export const EVENT_VERB: Record<EventType, string> = {
  "task.created": "Created task",
  "task.updated": "Updated task",
  "task.completed": "Completed task",
  "task.reopened": "Reopened task",
  "task.archived": "Archived task",
  "task.restored": "Restored task",
  "task.deleted": "Deleted task",
  "goal.created": "Created goal",
  "goal.updated": "Updated goal",
  "goal.status_changed": "Changed goal status",
  "goal.archived": "Archived goal",
  "goal.restored": "Restored goal",
  "goal.deleted": "Deleted goal",
  "milestone.created": "Added milestone",
  "milestone.completed": "Completed milestone",
  "milestone.reopened": "Reopened milestone",
  "milestone.deleted": "Removed milestone",
  "target.created": "Created target",
  "target.updated": "Updated target",
  "target.archived": "Archived target",
  "target.restored": "Restored target",
  "target.deleted": "Deleted target",
  "session.logged": "Logged",
  "session.deleted": "Deleted session",
  "routine.item_completed": "Completed routine",
  "routine.item_skipped": "Skipped routine",
  "routine.item_reset": "Reset routine",
  "project.created": "Created project",
  "project.updated": "Updated project",
  "project.status_changed": "Changed project status",
  "project.archived": "Archived project",
  "project.restored": "Restored project",
  "project.deleted": "Deleted project",
  "idea.created": "Captured idea",
  "idea.updated": "Updated idea",
  "idea.status_changed": "Moved idea",
  "idea.converted": "Converted idea to project",
  "idea.deleted": "Deleted idea",
  "decision.recorded": "Recorded decision",
  "decision.updated": "Updated decision",
  "decision.deleted": "Deleted decision",
  "note.created": "Created note",
  "note.updated": "Edited note",
  "note.archived": "Archived note",
  "note.restored": "Restored note",
  "note.deleted": "Deleted note",
  "skill.created": "Started tracking skill",
  "skill.updated": "Updated skill",
  "skill.level_changed": "Changed skill level",
  "skill.topic_completed": "Completed topic",
  "skill.archived": "Archived skill",
  "skill.restored": "Restored skill",
  "skill.deleted": "Deleted skill",
  "inbox.captured": "Captured",
  "inbox.processed": "Processed inbox item",
  "inbox.discarded": "Discarded inbox item",
  "entity.linked": "Linked",
  "entity.unlinked": "Unlinked",
};

export const EVENT_CATEGORIES: Record<string, { label: string; prefixes: string[] }> = {
  tasks: { label: "Tasks", prefixes: ["task."] },
  sessions: { label: "Sessions", prefixes: ["session.", "routine."] },
  goals: { label: "Goals & targets", prefixes: ["goal.", "milestone.", "target."] },
  projects: { label: "Projects & ideas", prefixes: ["project.", "idea.", "decision."] },
  knowledge: { label: "Notes & inbox", prefixes: ["note.", "inbox."] },
  skills: { label: "Skills", prefixes: ["skill."] },
};
